### ISSUE TITLE
Terraform provider version for AzureRM & AzureCAF to be updated

### ISSUE THREAD

**Issue by p9139010** [john0isaac/simple-flask-app-terraform#9]
azurerm-version - 3.47 no more available for deploying. have tried updating to 3.106 and azure caf version - 1.2.28. works fine. but haven't tried all the database or app insights. better to check the version before merging.

  required_providers {
    azurerm = {
      version = "~>3.106.0"
      source  = "hashicorp/azurerm"
    }
    azurecaf = {
      source  = "aztfmod/azurecaf"
      version = "~>1.2.28"
    }

**Comment by john0isaac** [comment]
Thank you for flagging, will work on a fix soon.
